# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sandbox.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'sandbox.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsandbox.proto\x12\x07sandbox\"5\n\x0fSolutionRequest\x12\x10\n\x08testPath\x18\x01 \x01(\t\x12\x10\n\x08solution\x18\x02 \x01(\t\"-\n\rSolutionReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\t2Q\n\nCodeRunner\x12\x43\n\x0fRunUserSolution\x12\x18.sandbox.SolutionRequest\x1a\x16.sandbox.SolutionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sandbox_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOLUTIONREQUEST']._serialized_start=26
  _globals['_SOLUTIONREQUEST']._serialized_end=79
  _globals['_SOLUTIONREPLY']._serialized_start=81
  _globals['_SOLUTIONREPLY']._serialized_end=126
  _globals['_CODERUNNER']._serialized_start=128
  _globals['_CODERUNNER']._serialized_end=209
# @@protoc_insertion_point(module_scope)
